"""empty message

Revision ID: cdbd8761f67b
Revises: 4a5f022aa3d3
Create Date: 2022-08-12 00:42:49.438095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbd8761f67b'
down_revision = '4a5f022aa3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('venue', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'venue')
    op.drop_column('events', 'image')
    # ### end Alembic commands ###
