"""empty message

Revision ID: 47d0d7de20bd
Revises: 833dfb4d8aac
Create Date: 2022-08-04 16:03:37.858020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d0d7de20bd'
down_revision = '833dfb4d8aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'default')
    # ### end Alembic commands ###
