"""empty message

Revision ID: 833dfb4d8aac
Revises: 2174a65dade3
Create Date: 2022-08-04 11:11:12.931402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833dfb4d8aac'
down_revision = '2174a65dade3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendarEvents')
    op.add_column('events', sa.Column('editable', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('calendarId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'calendars', ['calendarId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'calendarId')
    op.drop_column('events', 'editable')
    op.create_table('calendarEvents',
    sa.Column('calendarId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eventId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calendarId'], ['calendars.id'], name='calendarEvents_calendarId_fkey'),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], name='calendarEvents_eventId_fkey'),
    sa.PrimaryKeyConstraint('calendarId', 'eventId', name='calendarEvents_pkey')
    )
    # ### end Alembic commands ###
