"""empty message

Revision ID: 4a5f022aa3d3
Revises: 47d0d7de20bd
Create Date: 2022-08-05 23:25:56.910740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5f022aa3d3'
down_revision = '47d0d7de20bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'color')
    # ### end Alembic commands ###
