"""empty message

Revision ID: 7e871de8d01f
Revises: cdbd8761f67b
Create Date: 2022-08-25 16:23:58.659706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e871de8d01f'
down_revision = 'cdbd8761f67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('background', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'background')
    # ### end Alembic commands ###
